version: '3'
services:

  xman:
    build: .
    image: igrek5151/xman:latest
    container_name: xman
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./extensions.py:/extensions.py
